ci:
  autofix_prs: false
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v6.0.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: name-tests-test
  - repo: 'https://github.com/codespell-project/codespell'
    rev: v2.4.1
    hooks:
      - id: codespell
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.13.2
    hooks:
      - id: ruff
        args:
          - '--fix'
          - '--exit-non-zero-on-fix'
      - id: ruff-format
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - dask[distributed]==2024.8.1
          - globus-compute-sdk==2.27.*
          - proxystore==0.8.*
          - proxystore-ex==0.1.3
          - pydantic==2.8.*
          - types-psutil
          - types-redis
          - types-requests
